#!/bin/sh
unclutter &
xset -dpms
xset s off
matchbox-window-manager &
while true; do
 epiphany-browser -a --profile ~/.config http://127.0.0.1:9090
#chromium --noerrdialogs --kiosk http://127.0.0.1:9090
done
